version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/elasticache-redis-cluster
  - /modules/elasticache-redis-user
  - /modules/elasticache-redis-user-group
  schedule:
    interval: weekly
